In [5]:
import pandas as pd
import os
import pickle

In [33]:
# Define a file path (using os module) pointing to the pickled file from Exercise 1
# Create a Pandas DataFrame from the pickled file. Use the file path as an argument.
with open ('./data/locations_data_frame.pickle', 'rb') as handler:
    df2_unpickled = pickle.load(handler)

In [34]:
# Display the DataFrame
df2_unpickled

,mindate,maxdate,name,datacoverage,id,source
0,1919-07-01,2020-03-15,"Cleveland, NC 27013",0.9998,ZIP:27013,location_16.json
1,1946-10-01,2020-03-15,"Danbury, NC 27016",1.0000,ZIP:27016,location_16.json
2,1940-03-01,2020-03-15,"Dobson, NC 27017",1.0000,ZIP:27017,location_16.json
3,1957-11-13,2020-03-15,"East Bend, NC 27018",1.0000,ZIP:27018,location_16.json
4,1995-07-06,2020-03-15,"Germanton, NC 27019",0.9500,ZIP:27019,location_16.json
...,...,...,...,...,...,...
38855,1995-06-01,2020-03-15,"Advance, NC 27006",1.0000,ZIP:27006,location_15.json
38856,1995-07-06,2020-03-15,"Ararat, NC 27007",0.9500,ZIP:27007,location_15.json
38857,1995-07-06,2020-03-15,"Belews Creek, NC 27009",0.9500,ZIP:27009,location_15.json
38858,1995-07-06,2020-03-15,"Boonville, NC 27011",0.9500,ZIP:27011,location_15.json
38859,1995-07-06,2020-03-15,"Clemmons, NC 27012",1.0000,ZIP:27012,location_15.json

In [35]:
#Method 2
df3_unpickled = pd.read_pickle('./data/locations_data_frame2.pickle')
df3_unpickled

,mindate,maxdate,name,datacoverage,id,source
0,1919-07-01,2020-03-15,"Cleveland, NC 27013",0.9998,ZIP:27013,location_16.json
1,1946-10-01,2020-03-15,"Danbury, NC 27016",1.0000,ZIP:27016,location_16.json
2,1940-03-01,2020-03-15,"Dobson, NC 27017",1.0000,ZIP:27017,location_16.json
3,1957-11-13,2020-03-15,"East Bend, NC 27018",1.0000,ZIP:27018,location_16.json
4,1995-07-06,2020-03-15,"Germanton, NC 27019",0.9500,ZIP:27019,location_16.json
...,...,...,...,...,...,...
38855,1995-06-01,2020-03-15,"Advance, NC 27006",1.0000,ZIP:27006,location_15.json
38856,1995-07-06,2020-03-15,"Ararat, NC 27007",0.9500,ZIP:27007,location_15.json
38857,1995-07-06,2020-03-15,"Belews Creek, NC 27009",0.9500,ZIP:27009,location_15.json
38858,1995-07-06,2020-03-15,"Boonville, NC 27011",0.9500,ZIP:27011,location_15.json
38859,1995-07-06,2020-03-15,"Clemmons, NC 27012",1.0000,ZIP:27012,location_15.json